name: GO CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o resource-backend

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DHB_USERNAME }}
          password: ${{ secrets.DHB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --tag aliothmoon/resource-backend:latest .
          docker push aliothmoon/resource-backend:latest
