[server]
port = 8000

[log]
level = "info"
max_size = 5
max_backups = 10
max_age = 30
compress = true

[database]
host = "localhost"
port = 3306
username = "username"
password = "password"
name = "name"

[auth]
uploader_validation_url = "https://uploader.validation.example"
cdk_validation_url = "https://cdk.validation.example"